version: '2'
services:
  novnc:  
    image: latest
    environment:
      # Adjust to your screen size
      - DISPLAY_WIDTH=1180
      - DISPLAY_HEIGHT=860
    ports:
      - "80:8080"
    networks:
      - x11
networks:
  x11:
